using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GoWMS.Server.Models.Api
{
    public class Delivery_note_items
    {
		public Int64? Efidx { get; set; }
		public Int32? Efstatus { get; set; }
		public DateTime? Created { get; set; }
		public DateTime? Modified { get; set; }
		public Int64? Innovator { get; set; }
		public string Device { get; set; }
		public string Dn_No { get; set; }
		public Decimal? Seq_No { get; set; }
		public string Job_No { get; set; }
		public string Item_Code { get; set; }
		public Int32? Dn_Qty { get; set; }
		public string Dn_Um { get; set; }
		public DateTime? Dn_Date { get; set; }
		public string Status { get; set; }
		public string Customer_Code { get; set; }
		public string Batch_No { get; set; }
		public string Factory_Room { get; set; }
		public string Palette_No { get; set; }
		public Int32? Box_No { get; set; }
		public string Close_Flag { get; set; }
		public string Packeting_Code { get; set; }
		public Decimal? Dn_Weight { get; set; }
		public string Dn_Weight_Um { get; set; }
		public string Lot_No { get; set; }
		public string Store_Id { get; set; }
		public string Screen_Name { get; set; }
		public string Cust_Item_Code { get; set; }
		public string Vehicle_Code { get; set; }
		public string Vehicle_Link_Code { get; set; }
		public Decimal? Package_Weight { get; set; }
		public string App1_Flag { get; set; }
		public string App2_Flag { get; set; }
		public string App3_Flag { get; set; }
		public string App_Ag_Flag { get; set; }
		public DateTime? Net_Iron_Date { get; set; }
		public Decimal? Net_Iron_Number { get; set; }
		public string Created_T1_By { get; set; }
		public DateTime? Created_T1_On { get; set; }
		public string Approved_T1_By { get; set; }
		public DateTime? Approved_T1_On { get; set; }
		public string Net_Iron_Nc { get; set; }
		public DateTime? Infection_Date { get; set; }
		public string Tpc { get; set; }
		public string Ym { get; set; }
		public string Saureus { get; set; }
		public string Ecoli { get; set; }
		public string Coliform { get; set; }
		public string Bcereus { get; set; }
		public string Sallmonella { get; set; }
		public string Aw { get; set; }
		public string Remarks_Infection { get; set; }
		public string Infection_Nc { get; set; }
		public string Approved_T2_By { get; set; }
		public DateTime? Approved_T2_On { get; set; }
		public string Approved_T3_By { get; set; }
		public DateTime? Approved_T3_On { get; set; }
		public string Approved_Ag_By { get; set; }
		public DateTime? Approved_Ag_On { get; set; }
		public string Pk_No { get; set; }
		public Decimal? Pk_Seq { get; set; }
		public string Sticker_Code { get; set; }
		public string Screen_Code { get; set; }
		public string Sub_Customer_Code { get; set; }
		public string To_Pck_No { get; set; }
		public string Effect_Type { get; set; }
		public string Remarks { get; set; }
		public string Flag_Book { get; set; }
		public Decimal? Seq_Group { get; set; }
		public string Tank { get; set; }
		public string Brix { get; set; }
		public string Ph { get; set; }
		public string De { get; set; }
		public string Soii { get; set; }
		public string Bstar { get; set; }
		public string Awqa3 { get; set; }
		public string Remarks_Quality { get; set; }
		public string Quality_Nc { get; set; }
		public DateTime? Date_Quality { get; set; }
		public string Created_T2_By { get; set; }
		public DateTime? Created_T2_On { get; set; }
		public string Created_T3_By { get; set; }
		public DateTime? Created_T3_On { get; set; }
		public string Approved_Inv_By { get; set; }
		public DateTime? Approved_Inv_On { get; set; }
		public string Created_Inv_By { get; set; }
		public DateTime? Created_Inv_On { get; set; }
		public string App_Inv_Flag { get; set; }
		public string Remarks_Inv { get; set; }
		public string Item_Status { get; set; }
		public string Mj3 { get; set; }
		public string Bulkd3 { get; set; }
		public string Packbd3 { get; set; }
		public string Nc_Book { get; set; }
		public string Rack_No { get; set; }
		public string Black_Carbon { get; set; }
		public Decimal? Dup_Pck_No { get; set; }
		public Decimal? Pck_No { get; set; }
		public string Status_Load { get; set; }
		public DateTime? Packing_Date { get; set; }
		public Decimal? Yeast { get; set; }
		public Decimal? Mold { get; set; }
		public Decimal? Shelf_Life_Day { get; set; }
		public Decimal? Shelf_Life_Keep_In { get; set; }
		public DateTime? Shelf_Life_Date { get; set; }
		public DateTime? Shelf_Life_Keep_In_Date { get; set; }
		public Decimal? Palet_Sort { get; set; }
		public string Hit_Let { get; set; }
		public string Lot_Corn { get; set; }
		public string Tank_Ef { get; set; }
		public DateTime? Ref_Date { get; set; }
		public string Lstar { get; set; }
		public string Astar { get; set; }
		public string Remarks_Iss { get; set; }
		public DateTime? Injection_Date { get; set; }
		public DateTime? Spray_Date { get; set; }
		public string Batch_No_Cust { get; set; }
		public string Pallet_Go { get; set; }
		public string Status_Go { get; set; }
		public DateTime? Update_Date_Go { get; set; }
		public string Created_By { get; set; }
		public DateTime? Created_Date { get; set; }
	}
}
